<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>ElectricalStore.Api</RootNamespace>
    <AssemblyName>ElectricalStore.Api</AssemblyName>
    <UserSecretsId>ElectricalStore-dev-secrets</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ElectricalStore.Application\ElectricalStore.Application.csproj" />
    <ProjectReference Include="..\ElectricalStore.Infrastructure\ElectricalStore.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Permixa.AspNetCore" />
    <PackageReference Include="Permixa.Email.Resend" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
