export {
  registerCustomer,
  confirmCustomerEmail,
  resendCustomerEmailVerification,
  getCustomerProfile,
  updateCustomerProfile,
  changeCustomerPassword,
  requestCustomerPasswordReset,
  resetCustomerPassword,
  requestCustomerEmailChange,
  confirmCustomerEmailChange,
} from "./api";
export { accountProfileKeys } from "./query-keys";
export {
  customerRegisterFormSchema,
  updateProfileFormSchema,
  changePasswordFormSchema,
  forgotPasswordFormSchema,
  resetPasswordFormSchema,
  changeEmailFormSchema,
  PASSWORD_POLICY_HINT,
  type CustomerRegisterFormValues,
  type UpdateProfileFormValues,
  type ChangePasswordFormValues,
  type ForgotPasswordFormValues,
  type ResetPasswordFormValues,
  type ChangeEmailFormValues,
} from "./schemas";
export {
  getCustomerProfileErrorMessage,
  EMAIL_VERIFICATION_RESEND_GENERIC,
  PASSWORD_RESET_REQUEST_GENERIC,
} from "./errors";
export type {
  CustomerProfileDto,
  CustomerRegistrationRequest,
  CustomerRegistrationResponse,
  ConfirmEmailRequest,
  ConfirmEmailResponse,
  ResendEmailVerificationRequest,
  ResendEmailVerificationResponse,
  ForgotPasswordRequest,
  ForgotPasswordResponse,
  ResetPasswordRequest,
  ResetPasswordResponse,
  RequestEmailChangeRequest,
  RequestEmailChangeResponse,
  ConfirmEmailChangeRequest,
  ConfirmEmailChangeResponse,
  UpdateCustomerProfileRequest,
  ChangePasswordRequest,
  ChangePasswordResponse,
} from "./types";
